version: '3'
services:
    
  master:
    build: ./spark/spark_master
    image: rspark-master
    container_name: rspark-master
    hostname: rspark-master
    environment:
      - "SPARK_LOCAL_IP=rspark-master"
    ports:
      - "7077:7077"
      - "8080:8080"     # Master Web UI
      - "4040:4040"
      - "4041:4041"
    networks:
      rconnect-network:
#        ipv4_address: 10.5.0.5
      rspark-network:
#    volumes:
#      - rsparkdata:/opt/sparkdata

  worker1:
    image: rspark-master
    container_name: rspark-worker-1
    hostname: rspark-worker-1
    ports:
      - "8081:8081"     # Worker Web UI
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    environment:
      SPARK_LOCAL_IP: rspark-worker-1
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 2g
    networks:
      rconnect-network:
#        ipv4_address: 10.5.0.6
      rspark-network:
    depends_on:
      - master
#    volumes:
#      - rsparkdata:/opt/sparkdata
      
  worker2:
    image: rspark-master
    container_name: rspark-worker-2
    hostname: rspark-worker-2
    ports:
      - "8082:8081"     # Worker Web UI
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    environment:
      SPARK_LOCAL_IP: rspark-worker-2
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 2g
    networks:
      rconnect-network:
#        ipv4_address: 10.5.0.7
      rspark-network:
    depends_on:
      - master
#    volumes:
#      - rsparkdata:/opt/sparkdata

networks:
  rconnect-network:
  rspark-network:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 10.5.0.0/16