version: '3.5'
services:
    
  master:
    build: ./spark
    image: rspark:3.0.0
    restart: always
    command: /entrypoint/entrypoint-spark-master.sh
    ports:
      - "4040:4040"
#      - "7077:7077"
      - "8080:8080"     # Master Web UI
    networks:
      rconnect_network:

  worker1:
    image: rspark:3.0.0
    restart: always
    command: /entrypoint/entrypoint-spark-worker.sh
    environment:
      SPARK_CONF_DIR: /opt/spark/conf
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 4g
    depends_on:
      - master
    networks:
      rconnect_network:
      
  worker2:
    image: rspark:3.0.0
    restart: always
    command: /entrypoint/entrypoint-spark-worker.sh
    environment:
      SPARK_CONF_DIR: /opt/spark/conf
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 4g
    depends_on:
      - master
    networks:
      rconnect_network:
      
#  worker3:
#    image: rspark:3.0.0
#    restart: always
#    command: /entrypoint/entrypoint-spark-worker.sh
#    environment:
#      SPARK_CONF_DIR: /opt/spark/conf
#      SPARK_WORKER_CORES: 1
#      SPARK_WORKER_MEMORY: 2g
#    depends_on:
#      - master
#    networks:
#      rconnect_network:

networks:
  rconnect_network:
    name: rconnect
    driver: bridge

