version: '3.5'
services:
    
  master:
    build: ./spark/spark_master
    image: rspark-base
    restart: always
    container_name: rspark-master
    hostname: rspark-master
    command: /entrypoint/entrypoint-spark-master.sh
#    ports:
#      - "7077:7077"
#      - "8080:8080"     # Master Web UI
    networks:
      rconnect_network:

  worker1:
    image: rspark-base
    restart: always
    container_name: rspark-worker-1
    hostname: rspark-worker-1
    command: /entrypoint/entrypoint-spark-worker.sh
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 2g
    depends_on:
      - master
    networks:
      rconnect_network:
      
  worker2:
    image: rspark-base
    restart: always
    container_name: rspark-worker-2
    hostname: rspark-worker-2
    command: /entrypoint/entrypoint-spark-worker.sh
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 2g
    depends_on:
      - master
    networks:
      rconnect_network:
      
  worker3:
    image: rspark-base
    restart: always
    container_name: rspark-worker-3
    hostname: rspark-worker-3
    command: /entrypoint/entrypoint-spark-worker.sh
    environment:
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 2g
    depends_on:
      - master
    networks:
      rconnect_network:

networks:
  rconnect_network:
    name: rconnect
    driver: bridge

