version: '3.5'
services:

  postgres:
    image: rspark-postgres
    ports:
      - "5432:5432"     # Postgres
      
  hadoop:
    image: rspark-hadoop
    ports:
      - "9000:9000"     # Hadoop
      - "50070:50070"   # Hadoop UI
      
  hive:
    image: rspark-hive
    ports:
      - "10000:10000"
    depends_on:
      - hadoop
      - postgres
      
  rstudio:
    image: rspark-rstudio
    environment:
      - PASSWORD=rstudiojh
    ports:
      - "8787:8787"     # RStudio UI
    depends_on: 
      - hadoop
      - hive
